/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad;

import javax.swing.JOptionPane;

/**
 *
 * @author luisc
 */
public class DialogoInsertarEstudiante extends javax.swing.JDialog {

    /**
     * Creates new form DialogoInsertarEstudiante
     */
    public DialogoInsertarEstudiante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cCarrera = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cSemestre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cPromedio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Estudiante");
        setModal(true);
        setName("dlgNuevoEstudiante"); // NOI18N
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Nombre Completo");
        jPanel1.add(jLabel1);
        jPanel1.add(cNombre);

        jLabel2.setText("Carrera");
        jPanel1.add(jLabel2);
        jPanel1.add(cCarrera);

        jLabel3.setText("Semestre");
        jPanel1.add(jLabel3);
        jPanel1.add(cSemestre);

        jLabel4.setText("Promedio");
        jPanel1.add(jLabel4);
        jPanel1.add(cPromedio);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = cNombre.getText().trim().toUpperCase();
        String carrera = cCarrera.getText().trim().toUpperCase();
        int semestre = 0;
        try {
            semestre = Integer.parseInt(cSemestre.getText().trim());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El semestre debe ser numerico!");
            return ;
        }
        double prom = 0.0;
        try {
            prom = Double.parseDouble(cPromedio.getText().trim());
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El promedio debe ser numérico!");
            return ;
        }
        
        if (Universidad.insertarEstudianteEnLaBD(nombre, carrera, semestre, prom)) {
            int id = Universidad.obtenerIDDelUltimoEstudiante();
            JOptionPane.showMessageDialog(null, "Estudiante guardado con ID = " + id);
            
            cNombre.setText("");
            cCarrera.setText("");
            cSemestre.setText("");
            cPromedio.setText("");
            
            cNombre.requestFocus();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cCarrera;
    private javax.swing.JTextField cNombre;
    private javax.swing.JTextField cPromedio;
    private javax.swing.JTextField cSemestre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
