/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisc
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        panelEstudiantes = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manejador de Estudiantes");

        ArrayList<String[]> estuds = Universidad.obtenerTodosLosEstudiantes();
        String modelo[][] = new String[estuds.size()][5];

        for (int i = 0; i < estuds.size(); ++i) {
            for (int j = 0; j < 5; j++) {
                modelo[i][j] = estuds.get(i)[j];
            }
        }

        DefaultTableModel dataModel = new DefaultTableModel(
            modelo,
            new String [] {
                "ID", "Nombres", "Carrera", "Semestre", "Promedio"
            });
            tablaEstudiantes.setModel(dataModel);
            panelEstudiantes.setViewportView(tablaEstudiantes);

            getContentPane().add(panelEstudiantes, java.awt.BorderLayout.CENTER);

            jMenu1.setMnemonic('A');
            jMenu1.setText("Archivo");

            jMenuItem1.setText("Agregar Estudiante...");
            jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem1ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem1);

            jMenuItem3.setText("información de un estudiante...");
            jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem3ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem3);
            jMenu1.add(jSeparator1);

            jMenuItem2.setText("Salir");
            jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem2ActionPerformed(evt);
                }
            });
            jMenu1.add(jMenuItem2);

            jMenuBar1.add(jMenu1);

            setJMenuBar(jMenuBar1);

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DialogoInsertarEstudiante dlg = new DialogoInsertarEstudiante(this, true);
        dlg.setVisible(true);
        mostrarEstudiantes();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String nombreABuscar = JOptionPane.showInputDialog("Entre el  nombre del estudiante");
        Universidad.mostrarInformacionDeUnEstudiante(nombreABuscar.trim().toUpperCase());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    
    private void mostrarEstudiantes() {
        ArrayList<String[]> estuds = Universidad.obtenerTodosLosEstudiantes();
        
        // Creamos una matriz con los estudiantes y la columnas
        String modelo[][] = new String[estuds.size()][5];
        
        for (int i = 0; i < estuds.size(); ++i) {
            for (int j = 0; j < 5; j++) {
                modelo[i][j] = estuds.get(i)[j];
            }
        }
        
        DefaultTableModel dataModel = new DefaultTableModel(
                modelo, 
                new String [] {
                "ID", "Nombres", "Carrera", "Semestre", "Promedio"
            });
        tablaEstudiantes.setModel(dataModel);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Universidad.conectarBD();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        
                
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JScrollPane panelEstudiantes;
    private javax.swing.JTable tablaEstudiantes;
    // End of variables declaration//GEN-END:variables
}
